version: "2"
run:
  go: "1.23"
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - contextcheck
    - dupl
    - errcheck
    - errname
    - errorlint
    - gocyclo
    - godot
    - gosec
    - govet
    - misspell
    - nilerr
    - tparallel
    - unparam
    - unused
    - whitespace
    - noctx
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 3
    gocyclo:
      min-complexity: 15
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - goconst
          - gosec
          - testinggoroutine
        path: _test\.go
      - linters:
          - dupl
        path: commands/pagination/.*\.go
      - linters:
          - dupl
          - errcheck
          - unparam
        path: examples/
    paths:
      - third_party$
      - builtin$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
