package gmp

type Client interface {
	Authenticate(cmd *AuthenticateCommand) (resp *AuthenticateResponse, err error)
	GetConfigs(cmd *GetConfigsCommand) (resp *GetConfigsResponse, err error)
	GetScanners(cmd *GetScannersCommand) (resp *GetScannersResponse, err error)
	GetPreferences(cmd *GetPreferencesCommand) (resp *GetPreferencesResponse, err error)
	CreateConfig(cmd *CreateConfigCommand) (resp *CreateConfigResponse, err error)
	ModifyConfig(cmd *ModifyConfigCommand) (resp *ModifyConfigResponse, err error)
	CreateTask(cmd *CreateTaskCommand) (resp *CreateTaskResponse, err error)
	ModifyTask(cmd *ModifyTaskCommand) (resp *ModifyTaskResponse, err error)
	CreateTarget(cmd *CreateTargetCommand) (resp *CreateTargetResponse, err error)
	ModifyTarget(cmd *ModifyTargetCommand) (resp *ModifyTargetResponse, err error)
	GetTargets(cmd *GetTargetsCommand) (resp *GetTargetsResponse, err error)
	DeleteTarget(cmd *DeleteTargetCommand) (resp *DeleteTargetResponse, err error)
	GetPortLists(cmd *GetPortListsCommand) (resp *GetPortListsResponse, err error)
	StartTask(cmd *StartTaskCommand) (resp *StartTaskResponse, err error)
	GetTasks(cmd *GetTasksCommand) (resp *GetTasksResponse, err error)
	StopTask(cmd *StopTaskCommand) (resp *StopTaskResponse, err error)
	DeleteTask(cmd *DeleteTaskCommand) (resp *DeleteTaskResponse, err error)
	GetResults(cmd *GetResultsCommand) (resp *GetResultsResponse, err error)
	GetVulns(cmd *GetVulnsCommand) (resp *GetVulnsResponse, err error)
	CreateAlert(cmd *CreateAlertRequest) (resp *CreateAlertResponse, err error)
	GetAlerts(cmd *GetAlertsCommand) (resp *GetAlertsResponse, err error)
	ModifyAlert(cmd *ModifyAlertCommand) (resp *ModifyAlertResponse, err error)
	DeleteAlert(cmd *DeleteAlertCommand) (resp *DeleteAlertResponse, err error)
	TestAlert(cmd *TestAlertCommand) (resp *TestAlertResponse, err error)
	ResumeTask(cmd *ResumeTaskCommand) (resp *ResumeTaskResponse, err error)
	CreateAsset(cmd *CreateAssetCommand) (resp *CreateAssetResponse, err error)
	ModifyAsset(cmd *ModifyAssetCommand) (resp *ModifyAssetResponse, err error)
	GetAssets(cmd *GetAssetsCommand) (resp *GetAssetsResponse, err error)
	DeleteAsset(cmd *DeleteAssetCommand) (resp *DeleteAssetResponse, err error)
	CreateSchedule(cmd *CreateScheduleCommand) (resp *CreateScheduleResponse, err error)
	ModifySchedule(cmd *ModifyScheduleCommand) (resp *ModifyScheduleResponse, err error)
	GetSchedules(cmd *GetSchedulesCommand) (resp *GetSchedulesResponse, err error)
	DeleteSchedule(cmd *DeleteScheduleCommand) (resp *DeleteScheduleResponse, err error)
	CreateOverride(cmd *CreateOverrideCommand) (resp *CreateOverrideResponse, err error)
	DeleteOverride(cmd *DeleteOverrideCommand) (resp *DeleteOverrideResponse, err error)
	GetOverrides(cmd *GetOverridesCommand) (resp *GetOverridesResponse, err error)
}
