name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-lint-test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        run: go get .
      - name: Lint
        uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v8.0.0
        with:
          version: v1.60
      - name: Build
        run: go build -v ./...
      - name: Test with coverage
        run: go test -v -coverprofile=coverage.out ./...
      - name: Upload coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.out
          force-coverage-parser: go
